name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint with Flake8
      run: flake8 scripts/ tests/
    - name: Check formatting with Black
      run: black --check .
    - name: Check imports with isort
      run: isort --check-only .
    - name: Run tests
      env:
        GROQ_API_KEY: test_fake_key 
      run: pytest tests/